[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F411RETx"
# Or use OpenOCD:
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
rb = "run --release --bin"